# Generated by Django 5.2.15 on 2026-07-02 18:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id_audio', models.BigAutoField(db_column='idAudio', primary_key=True, serialize=False)),
                ('tempo', models.PositiveIntegerField(help_text='Duracao do audio em segundos.', validators=[django.core.validators.MaxValueValidator(86400)])),
                ('formato', models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4'), ('wav', 'WAV'), ('m4a', 'M4A'), ('ogg', 'OGG'), ('outro', 'Outro')], max_length=10)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
                'db_table': 'Audio',
                'indexes': [models.Index(fields=['formato'], name='audio_formato_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('formato__in', ['mp3', 'mp4', 'wav', 'm4a', 'ogg', 'outro'])), name='audio_formato_valido_chk'), models.CheckConstraint(condition=models.Q(('tempo__lte', 86400)), name='audio_tempo_max_chk')],
            },
        ),
        migrations.CreateModel(
            name='Transcricao',
            fields=[
                ('id_transcricao', models.BigAutoField(db_column='idTranscricao', primary_key=True, serialize=False)),
                ('texto_transcricao', models.TextField(db_column='textoTranscricao')),
                ('data_processamento', models.DateTimeField(db_column='dataProcessamento', default=django.utils.timezone.now)),
                ('texto_com_interlocutores', models.TextField(blank=True, db_column='textoComInterlocutores')),
                ('numero_interlocutores', models.PositiveSmallIntegerField(db_column='numeroInterlocutores', default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tem_diarizacao', models.BooleanField(db_column='temDiarizacao', default=False)),
                ('audio', models.ForeignKey(db_column='idAudio', on_delete=django.db.models.deletion.CASCADE, related_name='transcricoes', to='transcriptions.audio')),
            ],
            options={
                'verbose_name': 'transcricao',
                'verbose_name_plural': 'transcricoes',
                'db_table': 'Transcricao',
                'indexes': [models.Index(fields=['data_processamento'], name='transc_processamento_idx'), models.Index(fields=['tem_diarizacao'], name='transc_diarizacao_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('numero_interlocutores__lte', 100)), name='transc_interlocutores_max_chk')],
            },
        ),
    ]
